"""Use of Collections use cases.

Split by aggregate into ``proposal``, ``project``, ``journal`` and
``publication`` modules (with shared helpers in ``_shared``). Every use case
remains importable from this package, so callers keep using
``from app.use_of_collections.application.use_cases import X``.
"""

from __future__ import annotations

from app.use_of_collections.application.use_cases.journal import (
    AddLogEntryAttachment,
    AddLogEntryAttachmentInput,
    AddObjectLogEntry,
    AddObjectLogEntryInput,
    AddObjectOccurrenceEntry,
    AddObjectOccurrenceEntryInput,
    AddOccurrenceEntryAttachment,
    AddOccurrenceEntryAttachmentInput,
    EditObjectLogEntry,
    EditObjectLogEntryInput,
    EditObjectOccurrenceEntry,
    EditObjectOccurrenceEntryInput,
    GetObjectAccessLog,
    GetObjectAccessLogInput,
    GetObjectOccurrenceLog,
    GetObjectOccurrenceLogInput,
)
from app.use_of_collections.application.use_cases.project import (
    ApproveProposal,
    ApproveProposalInput,
    ApproveProposalOutput,
    CancelProject,
    CancelProjectInput,
    CancelProposal,
    CancelProposalInput,
    CancelProposalOutput,
    CompleteProject,
    CompleteProjectInput,
    StartProject,
    StartProjectInput,
)
from app.use_of_collections.application.use_cases.proposal import (
    AddRequestedObjects,
    AddRequestedObjectsInput,
    AssignProposal,
    AssignProposalInput,
    EditProposalDetails,
    EditProposalDetailsInput,
    ForwardProposal,
    ForwardProposalInput,
    RejectProposal,
    RejectProposalInput,
    RejectProposalOutput,
    RequestDocuments,
    RequestDocumentsInput,
    RequestedDocumentInput,
    RequestedObjectSnapshotInput,
    SendMessage,
    SendMessageInput,
    SubmitDocuments,
    SubmitDocumentsInput,
    SubmitProposal,
    SubmitProposalInput,
    SubmitProposalOutput,
)
from app.use_of_collections.application.use_cases.publication import (
    AddPublicationEntryAttachment,
    AddPublicationEntryAttachmentInput,
    AddPublicationLogEntry,
    AddPublicationLogEntryInput,
    EditPublicationLogEntry,
    EditPublicationLogEntryInput,
    GetPublicationLog,
    GetPublicationLogInput,
)

__all__ = [
    "AddLogEntryAttachment",
    "AddLogEntryAttachmentInput",
    "AddObjectLogEntry",
    "AddObjectLogEntryInput",
    "AddObjectOccurrenceEntry",
    "AddObjectOccurrenceEntryInput",
    "AddOccurrenceEntryAttachment",
    "AddOccurrenceEntryAttachmentInput",
    "AddPublicationEntryAttachment",
    "AddPublicationEntryAttachmentInput",
    "AddPublicationLogEntry",
    "AddPublicationLogEntryInput",
    "AddRequestedObjects",
    "AddRequestedObjectsInput",
    "ApproveProposal",
    "ApproveProposalInput",
    "ApproveProposalOutput",
    "AssignProposal",
    "AssignProposalInput",
    "CancelProject",
    "CancelProjectInput",
    "CancelProposal",
    "CancelProposalInput",
    "CancelProposalOutput",
    "CompleteProject",
    "CompleteProjectInput",
    "EditObjectLogEntry",
    "EditObjectLogEntryInput",
    "EditObjectOccurrenceEntry",
    "EditObjectOccurrenceEntryInput",
    "EditProposalDetails",
    "EditProposalDetailsInput",
    "EditPublicationLogEntry",
    "EditPublicationLogEntryInput",
    "ForwardProposal",
    "ForwardProposalInput",
    "GetObjectAccessLog",
    "GetObjectAccessLogInput",
    "GetObjectOccurrenceLog",
    "GetObjectOccurrenceLogInput",
    "GetPublicationLog",
    "GetPublicationLogInput",
    "RejectProposal",
    "RejectProposalInput",
    "RejectProposalOutput",
    "RequestDocuments",
    "RequestDocumentsInput",
    "RequestedDocumentInput",
    "RequestedObjectSnapshotInput",
    "SendMessage",
    "SendMessageInput",
    "StartProject",
    "StartProjectInput",
    "SubmitDocuments",
    "SubmitDocumentsInput",
    "SubmitProposal",
    "SubmitProposalInput",
    "SubmitProposalOutput",
]
