from enum import StrEnum


class WatchStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"


class RunStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class QueryStatus(StrEnum):
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class QueryType(StrEnum):
    INVENTORY = "INVENTORY"
    AUTHOR_INVENTORY = "AUTHOR_INVENTORY"
    INVENTORY_OBJECT = "INVENTORY_OBJECT"
    AUTHOR_OBJECT = "AUTHOR_OBJECT"


class CandidateStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    DISMISSED = "DISMISSED"
    SNOOZED = "SNOOZED"


class EvidenceType(StrEnum):
    INVENTORY_NUMBER = "INVENTORY_NUMBER"
    AUTHOR = "AUTHOR"
    OBJECT_NAME = "OBJECT_NAME"
    AUTHOR_INVENTORY = "AUTHOR_INVENTORY"
    INVENTORY_OBJECT = "INVENTORY_OBJECT"
    AUTHOR_OBJECT = "AUTHOR_OBJECT"


class EvidenceStrength(StrEnum):
    PRIMARY = "PRIMARY"
    SUPPORTING = "SUPPORTING"
    WEAK = "WEAK"


class DecisionType(StrEnum):
    CONFIRM = "CONFIRM"
    CORRECT_AND_CONFIRM = "CORRECT_AND_CONFIRM"
    DISMISS = "DISMISS"
    SNOOZE = "SNOOZE"


class AgentAnalysisStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AgentRecommendedAction(StrEnum):
    PRESENT_FOR_REVIEW = "PRESENT_FOR_REVIEW"
    SEARCH_INVENTORY_VARIANTS = "SEARCH_INVENTORY_VARIANTS"
    SEARCH_AUTHOR_VARIANTS = "SEARCH_AUTHOR_VARIANTS"
    SEARCH_TAXON_VARIANTS = "SEARCH_TAXON_VARIANTS"
    SEARCH_FULL_TEXT = "SEARCH_FULL_TEXT"
    DEPRIORITIZE = "DEPRIORITIZE"
    STOP_INSUFFICIENT_EVIDENCE = "STOP_INSUFFICIENT_EVIDENCE"


class AgentConfidence(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class AgentAnalysisFeedback(StrEnum):
    USEFUL = "USEFUL"
    PARTIALLY_USEFUL = "PARTIALLY_USEFUL"
    NOT_USEFUL = "NOT_USEFUL"
