"""Consolidated baseline schema

Single squashed baseline that creates the entire current schema (33 tables and
9 native PostgreSQL enum types) in one revision, replacing the previous 30
incremental migrations. Generated from ``Base.metadata`` (the unified data
model) — the authoritative snapshot for a freshly created database.

This is a fresh-start baseline: environments are always created from scratch,
so there is no data migration and no stamping of pre-existing databases.

Revision ID: 0000_consolidated_baseline
Revises:
Create Date: 2026-06-26 00:00:00.000000
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0000_consolidated_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE TYPE identity_group_name AS ENUM ('EXTERNAL', 'CURATORIAL', 'COLLECTIONS_MANAGEMENT', 'DIRECTION', 'SYS_ADMIN')")
    op.execute("CREATE TYPE use_type AS ENUM ('EXHIBITION', 'IN_SITU_VISIT', 'OTHER')")
    op.execute("CREATE TYPE use_status AS ENUM ('CREATED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')")
    op.execute("CREATE TYPE use_result AS ENUM ('COMPLETED', 'CANCELLED')")
    op.execute("CREATE TYPE use_event_type AS ENUM ('REQUESTED', 'STARTED', 'COMPLETED', 'CANCELLED')")
    op.execute("CREATE TYPE media_type AS ENUM ('DOCUMENT', 'IMAGE', 'VIDEO', 'OTHER')")
    op.execute("CREATE TYPE proposal_use_type AS ENUM ('EXHIBITION', 'IN_SITU_VISIT', 'OTHER')")
    op.execute("CREATE TYPE proposal_status AS ENUM ('SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')")
    op.execute("CREATE TYPE proposal_event_type AS ENUM ('SUBMITTED', 'ASSIGNED', 'FORWARDED', 'DOCUMENTS_REQUESTED', 'DOCUMENTS_SUBMITTED', 'REVIEW_STARTED', 'REFERRED_TO_DIRECTION', 'DIRECTION_CLARIFIED', 'APPROVED', 'REJECTED', 'CANCELLED')")
    op.execute("CREATE TABLE generated_narratives ( id VARCHAR(36) NOT NULL, record_id VARCHAR(36) NOT NULL, narrative TEXT NOT NULL, narrative_type VARCHAR(64) NOT NULL, resolution_source VARCHAR(32) NOT NULL, target_language VARCHAR(16) NOT NULL, creativity_temperature FLOAT NOT NULL, llm_model VARCHAR(128) NOT NULL, generated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id) )")
    op.execute("CREATE INDEX ix_generated_narratives_generated_at ON generated_narratives (generated_at)")
    op.execute("CREATE INDEX ix_generated_narratives_record_id ON generated_narratives (record_id)")
    op.execute("CREATE TABLE in_situ_visit_records ( id VARCHAR(36) NOT NULL, code VARCHAR(64) NOT NULL, visit_begin_date DATE NOT NULL, visit_end_date DATE NOT NULL, visitor_name VARCHAR(255) NOT NULL, place_name VARCHAR(255) NOT NULL, generated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id) )")
    op.execute("CREATE INDEX ix_in_situ_visit_records_code ON in_situ_visit_records (code)")
    op.execute("CREATE INDEX ix_in_situ_visit_records_generated_at ON in_situ_visit_records (generated_at)")
    op.execute("CREATE TABLE identity_users ( id VARCHAR(36) NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, PRIMARY KEY (id), UNIQUE (email) )")
    op.execute("CREATE TABLE identity_groups ( id VARCHAR(36) NOT NULL, name identity_group_name NOT NULL, PRIMARY KEY (id) )")
    op.execute("CREATE TABLE public_proposal_submissions ( id VARCHAR(36) NOT NULL, token VARCHAR(64) NOT NULL, citizen_name VARCHAR(120) NOT NULL, citizen_email VARCHAR(180) NOT NULL, subject VARCHAR(160) NOT NULL, body TEXT NOT NULL, consent BOOLEAN NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, confirmed_at TIMESTAMP WITH TIME ZONE, proposal_reference VARCHAR(32), PRIMARY KEY (id) )")
    op.execute("CREATE INDEX ix_public_proposal_submissions_citizen_email ON public_proposal_submissions (citizen_email)")
    op.execute("CREATE UNIQUE INDEX ix_public_proposal_submissions_token ON public_proposal_submissions (token)")
    op.execute("CREATE INDEX ix_public_proposal_submissions_created_at ON public_proposal_submissions (created_at)")
    op.execute("CREATE INDEX ix_public_proposal_submissions_status ON public_proposal_submissions (status)")
    op.execute("CREATE TABLE collection_use_projects ( id VARCHAR(36) NOT NULL, reference_number VARCHAR(12) NOT NULL, title VARCHAR(255) NOT NULL, purpose TEXT NOT NULL, note TEXT, request_note TEXT, proposal_id VARCHAR(36), type use_type NOT NULL, intended_use_description TEXT DEFAULT '' NOT NULL, status use_status NOT NULL, result use_result, authorised_by VARCHAR(36), authorised_at TIMESTAMP WITH TIME ZONE, begin_date DATE NOT NULL, end_date DATE NOT NULL, requested_by VARCHAR(36) NOT NULL, PRIMARY KEY (id) )")
    op.execute("CREATE INDEX ix_collection_use_projects_proposal_id ON collection_use_projects (proposal_id)")
    op.execute("CREATE INDEX ix_collection_use_projects_requested_by ON collection_use_projects (requested_by)")
    op.execute("CREATE UNIQUE INDEX ix_collection_use_projects_reference_number ON collection_use_projects (reference_number)")
    op.execute("CREATE TABLE collection_use_objects ( id VARCHAR(36) NOT NULL, project_id VARCHAR(36) NOT NULL, inventory_number VARCHAR(128) NOT NULL, display_title VARCHAR(255), object_name VARCHAR(255), brief_description_snapshot TEXT, category VARCHAR(255) NOT NULL, description TEXT NOT NULL, requested_at TIMESTAMP WITH TIME ZONE NOT NULL, requested_by VARCHAR(36) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(project_id) REFERENCES collection_use_projects (id) )")
    op.execute("CREATE INDEX ix_collection_use_objects_project_id ON collection_use_objects (project_id)")
    op.execute("CREATE INDEX ix_collection_use_objects_requested_by ON collection_use_objects (requested_by)")
    op.execute("CREATE TABLE proposals ( id VARCHAR(36) NOT NULL, reference_number VARCHAR(17) NOT NULL, title VARCHAR(255), collection_use_project_id VARCHAR(36) NOT NULL, type proposal_use_type, intended_use_description TEXT DEFAULT '' NOT NULL, begin_date DATE, end_date DATE, status proposal_status NOT NULL, requested_by VARCHAR(36) NOT NULL, assigned_to VARCHAR(36), submitted_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id) )")
    op.execute("CREATE INDEX ix_proposals_collection_use_project_id ON proposals (collection_use_project_id)")
    op.execute("CREATE INDEX ix_proposals_requested_by ON proposals (requested_by)")
    op.execute("CREATE INDEX ix_proposals_assigned_to ON proposals (assigned_to)")
    op.execute("CREATE UNIQUE INDEX ix_proposals_reference_number ON proposals (reference_number)")
    op.execute("CREATE TABLE conversations ( id VARCHAR(36) NOT NULL, proposal_id VARCHAR(36) NOT NULL, external_message_id VARCHAR(255), PRIMARY KEY (id) )")
    op.execute("CREATE UNIQUE INDEX ix_conversations_external_message_id ON conversations (external_message_id)")
    op.execute("CREATE UNIQUE INDEX ix_conversations_proposal_id ON conversations (proposal_id)")
    op.execute("CREATE TABLE in_situ_visit_reports ( id VARCHAR(36) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, created_by VARCHAR(36) NOT NULL, project_id VARCHAR(36) NOT NULL, narrative_id VARCHAR(36) NOT NULL, in_situ_visit_record_id VARCHAR(36) NOT NULL, PRIMARY KEY (id) )")
    op.execute("CREATE INDEX ix_in_situ_visit_reports_project_id ON in_situ_visit_reports (project_id)")
    op.execute("CREATE INDEX ix_in_situ_visit_reports_created_at ON in_situ_visit_reports (created_at)")
    op.execute("CREATE TABLE requested_object_records ( id VARCHAR(36) NOT NULL, visit_record_id VARCHAR(36) NOT NULL, source_id VARCHAR(255) NOT NULL, description TEXT NOT NULL, position INTEGER NOT NULL, PRIMARY KEY (id), FOREIGN KEY(visit_record_id) REFERENCES in_situ_visit_records (id) )")
    op.execute("CREATE INDEX ix_requested_object_records_visit_record_id ON requested_object_records (visit_record_id)")
    op.execute("CREATE TABLE in_situ_occurrence_records ( id VARCHAR(36) NOT NULL, visit_record_id VARCHAR(36) NOT NULL, source_id VARCHAR(255) NOT NULL, description TEXT NOT NULL, position INTEGER NOT NULL, PRIMARY KEY (id), FOREIGN KEY(visit_record_id) REFERENCES in_situ_visit_records (id) )")
    op.execute("CREATE INDEX ix_in_situ_occurrence_records_visit_record_id ON in_situ_occurrence_records (visit_record_id)")
    op.execute("CREATE TABLE in_situ_log_records ( id VARCHAR(36) NOT NULL, visit_record_id VARCHAR(36) NOT NULL, source_id VARCHAR(255) NOT NULL, description TEXT NOT NULL, position INTEGER NOT NULL, PRIMARY KEY (id), FOREIGN KEY(visit_record_id) REFERENCES in_situ_visit_records (id) )")
    op.execute("CREATE INDEX ix_in_situ_log_records_visit_record_id ON in_situ_log_records (visit_record_id)")
    op.execute("CREATE TABLE in_situ_publication_records ( id VARCHAR(36) NOT NULL, visit_record_id VARCHAR(36) NOT NULL, source_id VARCHAR(255) NOT NULL, description TEXT NOT NULL, position INTEGER NOT NULL, PRIMARY KEY (id), FOREIGN KEY(visit_record_id) REFERENCES in_situ_visit_records (id) )")
    op.execute("CREATE INDEX ix_in_situ_publication_records_visit_record_id ON in_situ_publication_records (visit_record_id)")
    op.execute("CREATE TABLE identity_permissions ( id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL, group_id VARCHAR(36) NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_permission_user_group UNIQUE (user_id, group_id), FOREIGN KEY(user_id) REFERENCES identity_users (id), FOREIGN KEY(group_id) REFERENCES identity_groups (id) )")
    op.execute("CREATE INDEX ix_identity_permissions_group_id ON identity_permissions (group_id)")
    op.execute("CREATE INDEX ix_identity_permissions_user_id ON identity_permissions (user_id)")
    op.execute("CREATE TABLE use_events ( id SERIAL NOT NULL, project_id VARCHAR(36) NOT NULL, occurred_at TIMESTAMP WITH TIME ZONE NOT NULL, type use_event_type NOT NULL, triggered_by VARCHAR(36) NOT NULL, note TEXT, PRIMARY KEY (id), FOREIGN KEY(project_id) REFERENCES collection_use_projects (id) )")
    op.execute("CREATE INDEX ix_use_events_project_id ON use_events (project_id)")
    op.execute("CREATE INDEX ix_use_events_triggered_by ON use_events (triggered_by)")
    op.execute("CREATE TABLE object_access_logs ( id VARCHAR(36) NOT NULL, reference_number VARCHAR(32) NOT NULL, project_id VARCHAR(36) NOT NULL, date_conclusion TIMESTAMP WITH TIME ZONE, curator VARCHAR(36), PRIMARY KEY (id), UNIQUE (reference_number), FOREIGN KEY(project_id) REFERENCES collection_use_projects (id) )")
    op.execute("CREATE UNIQUE INDEX ix_object_access_logs_project_id ON object_access_logs (project_id)")
    op.execute("CREATE TABLE object_occurrence_logs ( id VARCHAR(36) NOT NULL, reference_number VARCHAR(32) NOT NULL, project_id VARCHAR(36) NOT NULL, date_conclusion TIMESTAMP WITH TIME ZONE, curator VARCHAR(36), PRIMARY KEY (id), UNIQUE (reference_number), FOREIGN KEY(project_id) REFERENCES collection_use_projects (id) )")
    op.execute("CREATE UNIQUE INDEX ix_object_occurrence_logs_project_id ON object_occurrence_logs (project_id)")
    op.execute("CREATE TABLE publication_logs ( id VARCHAR(36) NOT NULL, reference_number VARCHAR(32) NOT NULL, project_id VARCHAR(36) NOT NULL, curator VARCHAR(36), PRIMARY KEY (id), UNIQUE (reference_number), FOREIGN KEY(project_id) REFERENCES collection_use_projects (id) )")
    op.execute("CREATE UNIQUE INDEX ix_publication_logs_project_id ON publication_logs (project_id)")
    op.execute("CREATE TABLE proposal_events ( id SERIAL NOT NULL, proposal_id VARCHAR(36) NOT NULL, occurred_at TIMESTAMP WITH TIME ZONE NOT NULL, type proposal_event_type NOT NULL, triggered_by VARCHAR(36) NOT NULL, note TEXT, PRIMARY KEY (id), FOREIGN KEY(proposal_id) REFERENCES proposals (id) )")
    op.execute("CREATE INDEX ix_proposal_events_triggered_by ON proposal_events (triggered_by)")
    op.execute("CREATE INDEX ix_proposal_events_proposal_id ON proposal_events (proposal_id)")
    op.execute("CREATE TABLE requested_documents ( id VARCHAR(36) NOT NULL, proposal_id VARCHAR(36) NOT NULL, type VARCHAR(128) NOT NULL, description TEXT NOT NULL, requested_at TIMESTAMP WITH TIME ZONE NOT NULL, requested_by VARCHAR(36) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(proposal_id) REFERENCES proposals (id) )")
    op.execute("CREATE INDEX ix_requested_documents_proposal_id ON requested_documents (proposal_id)")
    op.execute("CREATE INDEX ix_requested_documents_requested_by ON requested_documents (requested_by)")
    op.execute("CREATE TABLE proposal_requested_objects ( id VARCHAR(36) NOT NULL, proposal_id VARCHAR(36) NOT NULL, inventory_number VARCHAR(128) NOT NULL, display_title VARCHAR(255), object_name VARCHAR(255), brief_description_snapshot TEXT, category VARCHAR(255) NOT NULL, description TEXT NOT NULL, requested_at TIMESTAMP WITH TIME ZONE NOT NULL, requested_by VARCHAR(36) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(proposal_id) REFERENCES proposals (id) )")
    op.execute("CREATE INDEX ix_proposal_requested_objects_proposal_id ON proposal_requested_objects (proposal_id)")
    op.execute("CREATE INDEX ix_proposal_requested_objects_requested_by ON proposal_requested_objects (requested_by)")
    op.execute("CREATE TABLE documents ( id VARCHAR(36) NOT NULL, proposal_id VARCHAR(36) NOT NULL, type VARCHAR(128) NOT NULL, file_name VARCHAR(255) NOT NULL, file_reference VARCHAR(255) NOT NULL, submitted_at TIMESTAMP WITH TIME ZONE NOT NULL, submitted_by VARCHAR(36) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(proposal_id) REFERENCES proposals (id) )")
    op.execute("CREATE INDEX ix_documents_submitted_by ON documents (submitted_by)")
    op.execute("CREATE INDEX ix_documents_proposal_id ON documents (proposal_id)")
    op.execute("CREATE TABLE messages ( id VARCHAR(36) NOT NULL, conversation_id VARCHAR(36) NOT NULL, sent_at TIMESTAMP WITH TIME ZONE NOT NULL, sender VARCHAR(255) NOT NULL, recipient VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, body TEXT NOT NULL, PRIMARY KEY (id), FOREIGN KEY(conversation_id) REFERENCES conversations (id) )")
    op.execute("CREATE INDEX ix_messages_conversation_id ON messages (conversation_id)")
    op.execute("CREATE TABLE in_situ_occurrence_attachment_records ( id VARCHAR(36) NOT NULL, occurrence_id VARCHAR(36) NOT NULL, source_id VARCHAR(255) NOT NULL, description TEXT NOT NULL, reference VARCHAR(1024) NOT NULL, position INTEGER NOT NULL, PRIMARY KEY (id), FOREIGN KEY(occurrence_id) REFERENCES in_situ_occurrence_records (id) )")
    op.execute("CREATE INDEX ix_in_situ_occurrence_attachment_records_occurrence_id ON in_situ_occurrence_attachment_records (occurrence_id)")
    op.execute("CREATE TABLE in_situ_log_attachment_records ( id VARCHAR(36) NOT NULL, log_id VARCHAR(36) NOT NULL, source_id VARCHAR(255) NOT NULL, description TEXT NOT NULL, reference VARCHAR(1024) NOT NULL, position INTEGER NOT NULL, PRIMARY KEY (id), FOREIGN KEY(log_id) REFERENCES in_situ_log_records (id) )")
    op.execute("CREATE INDEX ix_in_situ_log_attachment_records_log_id ON in_situ_log_attachment_records (log_id)")
    op.execute("CREATE TABLE in_situ_publication_attachment_records ( id VARCHAR(36) NOT NULL, publication_id VARCHAR(36) NOT NULL, source_id VARCHAR(255) NOT NULL, description TEXT NOT NULL, reference VARCHAR(1024) NOT NULL, position INTEGER NOT NULL, PRIMARY KEY (id), FOREIGN KEY(publication_id) REFERENCES in_situ_publication_records (id) )")
    op.execute("CREATE INDEX ix_in_situ_publication_attachment_records_publication_id ON in_situ_publication_attachment_records (publication_id)")
    op.execute("CREATE TABLE object_log_entries ( id VARCHAR(36) NOT NULL, access_log_id VARCHAR(36) NOT NULL, number_of_objects INTEGER NOT NULL, added_at TIMESTAMP WITH TIME ZONE NOT NULL, added_by VARCHAR(36) NOT NULL, observations TEXT, collection_use_object_id VARCHAR(36) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(access_log_id) REFERENCES object_access_logs (id) )")
    op.execute("CREATE INDEX ix_object_log_entries_access_log_id ON object_log_entries (access_log_id)")
    op.execute("CREATE INDEX ix_object_log_entries_added_by ON object_log_entries (added_by)")
    op.execute("CREATE INDEX ix_object_log_entries_collection_use_object_id ON object_log_entries (collection_use_object_id)")
    op.execute("CREATE TABLE object_occurrence_entries ( id VARCHAR(36) NOT NULL, occurrence_log_id VARCHAR(36) NOT NULL, number_of_objects INTEGER NOT NULL, occurrence_date TIMESTAMP WITH TIME ZONE NOT NULL, location VARCHAR(255) NOT NULL, reported_by VARCHAR(36) NOT NULL, detailed_description TEXT NOT NULL, testimonial TEXT, collection_use_object_id VARCHAR(36) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(occurrence_log_id) REFERENCES object_occurrence_logs (id) )")
    op.execute("CREATE INDEX ix_object_occurrence_entries_collection_use_object_id ON object_occurrence_entries (collection_use_object_id)")
    op.execute("CREATE INDEX ix_object_occurrence_entries_occurrence_log_id ON object_occurrence_entries (occurrence_log_id)")
    op.execute("CREATE INDEX ix_object_occurrence_entries_reported_by ON object_occurrence_entries (reported_by)")
    op.execute("CREATE TABLE publication_log_entries ( id VARCHAR(36) NOT NULL, publication_log_id VARCHAR(36) NOT NULL, added_at TIMESTAMP WITH TIME ZONE NOT NULL, added_by VARCHAR(36) NOT NULL, note TEXT NOT NULL, PRIMARY KEY (id), FOREIGN KEY(publication_log_id) REFERENCES publication_logs (id) )")
    op.execute("CREATE INDEX ix_publication_log_entries_added_by ON publication_log_entries (added_by)")
    op.execute("CREATE INDEX ix_publication_log_entries_publication_log_id ON publication_log_entries (publication_log_id)")
    op.execute("CREATE TABLE message_attachments ( id SERIAL NOT NULL, message_id VARCHAR(36) NOT NULL, document_id VARCHAR(36) NOT NULL, file_name VARCHAR(255) NOT NULL, PRIMARY KEY (id), FOREIGN KEY(message_id) REFERENCES messages (id) )")
    op.execute("CREATE INDEX ix_message_attachments_message_id ON message_attachments (message_id)")
    op.execute("CREATE TABLE log_entry_attachments ( id SERIAL NOT NULL, entry_id VARCHAR(36) NOT NULL, file_reference VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, media_type media_type NOT NULL, uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL, note TEXT, PRIMARY KEY (id), FOREIGN KEY(entry_id) REFERENCES object_log_entries (id) )")
    op.execute("CREATE INDEX ix_log_entry_attachments_entry_id ON log_entry_attachments (entry_id)")
    op.execute("CREATE TABLE occurrence_entry_attachments ( id SERIAL NOT NULL, entry_id VARCHAR(36) NOT NULL, file_reference VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, media_type media_type NOT NULL, uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL, note TEXT, PRIMARY KEY (id), FOREIGN KEY(entry_id) REFERENCES object_occurrence_entries (id) )")
    op.execute("CREATE INDEX ix_occurrence_entry_attachments_entry_id ON occurrence_entry_attachments (entry_id)")
    op.execute("CREATE TABLE publication_entry_attachments ( id SERIAL NOT NULL, entry_id VARCHAR(36) NOT NULL, file_reference VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, media_type media_type NOT NULL, uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL, note TEXT, PRIMARY KEY (id), FOREIGN KEY(entry_id) REFERENCES publication_log_entries (id) )")
    op.execute("CREATE INDEX ix_publication_entry_attachments_entry_id ON publication_entry_attachments (entry_id)")


def downgrade() -> None:
    op.execute("DROP TABLE publication_entry_attachments")
    op.execute("DROP TABLE occurrence_entry_attachments")
    op.execute("DROP TABLE log_entry_attachments")
    op.execute("DROP TABLE message_attachments")
    op.execute("DROP TABLE publication_log_entries")
    op.execute("DROP TABLE object_occurrence_entries")
    op.execute("DROP TABLE object_log_entries")
    op.execute("DROP TABLE in_situ_publication_attachment_records")
    op.execute("DROP TABLE in_situ_log_attachment_records")
    op.execute("DROP TABLE in_situ_occurrence_attachment_records")
    op.execute("DROP TABLE messages")
    op.execute("DROP TABLE documents")
    op.execute("DROP TABLE proposal_requested_objects")
    op.execute("DROP TABLE requested_documents")
    op.execute("DROP TABLE proposal_events")
    op.execute("DROP TABLE publication_logs")
    op.execute("DROP TABLE object_occurrence_logs")
    op.execute("DROP TABLE object_access_logs")
    op.execute("DROP TABLE use_events")
    op.execute("DROP TABLE identity_permissions")
    op.execute("DROP TABLE in_situ_publication_records")
    op.execute("DROP TABLE in_situ_log_records")
    op.execute("DROP TABLE in_situ_occurrence_records")
    op.execute("DROP TABLE requested_object_records")
    op.execute("DROP TABLE in_situ_visit_reports")
    op.execute("DROP TABLE conversations")
    op.execute("DROP TABLE proposals")
    op.execute("DROP TABLE collection_use_objects")
    op.execute("DROP TABLE collection_use_projects")
    op.execute("DROP TABLE public_proposal_submissions")
    op.execute("DROP TABLE identity_groups")
    op.execute("DROP TABLE identity_users")
    op.execute("DROP TABLE in_situ_visit_records")
    op.execute("DROP TABLE generated_narratives")
    op.execute("DROP TYPE identity_group_name")
    op.execute("DROP TYPE use_type")
    op.execute("DROP TYPE use_status")
    op.execute("DROP TYPE use_result")
    op.execute("DROP TYPE use_event_type")
    op.execute("DROP TYPE media_type")
    op.execute("DROP TYPE proposal_use_type")
    op.execute("DROP TYPE proposal_status")
    op.execute("DROP TYPE proposal_event_type")
