from enum import StrEnum


class NotificationKind(StrEnum):
    PROPOSAL_SUBMITTED = "PROPOSAL_SUBMITTED"
    PROPOSAL_ASSIGNED = "PROPOSAL_ASSIGNED"
    PROPOSAL_FORWARDED = "PROPOSAL_FORWARDED"
    PROPOSAL_REFERRED_TO_DIRECTION = "PROPOSAL_REFERRED_TO_DIRECTION"
    PROPOSAL_RETURNED_TO_STAFF = "PROPOSAL_RETURNED_TO_STAFF"
    PROPOSAL_TAKEN_OVER = "PROPOSAL_TAKEN_OVER"
    PROPOSAL_DOCUMENTS_SUBMITTED = "PROPOSAL_DOCUMENTS_SUBMITTED"
    PROPOSAL_CORRECTIONS_SUBMITTED = "PROPOSAL_CORRECTIONS_SUBMITTED"
    MUSEUM_QUESTION_SUBMITTED = "MUSEUM_QUESTION_SUBMITTED"
    MUSEUM_QUESTION_FORWARDED = "MUSEUM_QUESTION_FORWARDED"
    MUSEUM_QUESTION_RESPONSE_OVERDUE = "MUSEUM_QUESTION_RESPONSE_OVERDUE"
    SCIENTIFIC_RETURN_CANDIDATES_FOUND = "SCIENTIFIC_RETURN_CANDIDATES_FOUND"


class RelatedResourceType(StrEnum):
    PROPOSAL = "PROPOSAL"
    PROJECT = "PROJECT"
    MUSEUM_QUESTION = "MUSEUM_QUESTION"
