from enum import StrEnum


class NotificationKind(StrEnum):
    PROPOSAL_SUBMITTED = "PROPOSAL_SUBMITTED"
    PROPOSAL_ASSIGNED = "PROPOSAL_ASSIGNED"
    PROPOSAL_FORWARDED = "PROPOSAL_FORWARDED"
    PROPOSAL_TAKEN_OVER = "PROPOSAL_TAKEN_OVER"
    PROPOSAL_DOCUMENTS_SUBMITTED = "PROPOSAL_DOCUMENTS_SUBMITTED"
    PROPOSAL_CORRECTIONS_SUBMITTED = "PROPOSAL_CORRECTIONS_SUBMITTED"
    MUSEUM_QUESTION_SUBMITTED = "MUSEUM_QUESTION_SUBMITTED"
    MUSEUM_QUESTION_FORWARDED = "MUSEUM_QUESTION_FORWARDED"


class RelatedResourceType(StrEnum):
    PROPOSAL = "PROPOSAL"
    PROJECT = "PROJECT"
    MUSEUM_QUESTION = "MUSEUM_QUESTION"
