from enum import StrEnum


class NotificationKind(StrEnum):
    PROPOSAL_SUBMITTED = "PROPOSAL_SUBMITTED"
    PROPOSAL_ASSIGNED = "PROPOSAL_ASSIGNED"
    PROPOSAL_FORWARDED = "PROPOSAL_FORWARDED"
    PROPOSAL_DOCUMENTS_SUBMITTED = "PROPOSAL_DOCUMENTS_SUBMITTED"
    PROPOSAL_CORRECTIONS_SUBMITTED = "PROPOSAL_CORRECTIONS_SUBMITTED"


class RelatedResourceType(StrEnum):
    PROPOSAL = "PROPOSAL"
    PROJECT = "PROJECT"
